src/hash/crc32.h File Reference
#include <math.h>
#include <assert.h>
Typedefs
typedef unsigned int CRC32_t
Functions
CRC32_t crc_add (CRC32_t crc, const char *data, ssize_t data_size)
Calcs CRC32 hash.
Typedef Documentation
CRC32_t
typedef unsigned int CRC32_t
Definition at line 7 of file crc32.h.
Function Documentation
crc_add()
CRC32_t crc_add (CRC32_t crc, const char * data, ssize_t data_size)
Calcs CRC32 hash.
Parameters
crc init value
data
data_size
Returns
CRC32_t
Definition at line 3 of file crc32.cpp.
                                                                  {
    assert(data);
    while (data_size--) {
        crc = (crc << 8) ^ crc32_table[((crc >> 24) ^ *data) & 255];
        data++;
    }
    return crc;
}
Referenced by stk_data_hash_calc(), stk_data_hash_push(), and stk_struct_hash_calc().