src/checksum/hash.h File Reference
#include <math.h>
#include <assert.h>
Classes
struct Hash
Contains polynomial hash informations.
Functions
Hash hash_init (size_t elem_size)
Creates hash for empty stack.
void hash_push (Hash *hash, const void *elem)
Calculates new hash by pushing one element.
void hash_create (Hash *hash, const void *data, const size_t len)
Calculates new hash from stack.
Function Documentation
hash_create()
void hash_create (Hash * hash, const void * data, const size_t len)
Calculates new hash from stack.
Parameters
hash
data stack array
len
Definition at line 16 of file hash.cpp.
                                                           {
    *hash = hash_init(hash->elem_size);
    for (size_t i = 0; i < hash->elem_size * len; i++) {
        hash->hash = (hash->hash + *((const char*)data + i) * hash->coeff_pow_len) % hash->MOD;
        hash->coeff_pow_len = (hash->coeff_pow_len * hash->COEFF) % hash->MOD;
    }
}
References Hash::COEFF, Hash::coeff_pow_len, Hash::elem_size, Hash::hash, hash_init(), and Hash::MOD.
Referenced by stk_pop(), and stk_verify().
hash_init()
Hash hash_init (size_t elem_size)
Creates hash for empty stack.
Parameters
elem_size stack element sizeof()
Returns
Hash
Definition at line 3 of file hash.cpp.
                                 {
    Hash hash = {};
    hash.elem_size = elem_size;
    return hash;
}
References Hash::elem_size.
Referenced by hash_create(), stk_ctor(), and stk_verify().
hash_push()
void hash_push (Hash * hash, const void * elem)
Calculates new hash by pushing one element.
Parameters
hash
elem pushed element
Definition at line 9 of file hash.cpp.
                                             {
    for (size_t i = 0; i < hash->elem_size; i++) {
        hash->hash = (hash->hash + *((const char*)elem + i) * hash->coeff_pow_len) % hash->MOD;
        hash->coeff_pow_len = (hash->coeff_pow_len * hash->COEFF) % hash->MOD;
    }
}
References Hash::COEFF, Hash::coeff_pow_len, Hash::elem_size, Hash::hash, and Hash::MOD.
Referenced by stk_push().