src/log/log.cpp File Reference
#include "log.h"
Functions
int stk_log_printf (LogFileData *log_file, const char *format,...)
Prints data in printf format to log file.
bool stk_log_open_file (LogFileData *log_file, const char *mode)
Opens log file.
bool stk_log_close_file (LogFileData *log_file)
Closes log fle.
Function Documentation
stk_log_close_file()
bool stk_log_close_file (LogFileData * log)
Closes log fle.
Parameters
log
Returns
true success
false failure
Definition at line 39 of file log.cpp.
                                               {
    if (fclose(log_file->file) != 0) {
        perror("Error closing log_file file");
        return false;
    }
    log_file->file = nullptr;
    return true;
}
References LogFileData::file, and log_file.
Referenced by main(), and stk_log_printf().
stk_log_open_file()
bool stk_log_open_file (LogFileData * log, const char * mode = "ab")
Opens log file.
Parameters
log
mode fopen() mode
Returns
true success
false failure
Definition at line 26 of file log.cpp.
                                                                {
    assert(log_file);
    log_file->file = fopen(log_file->filename, mode);
    if (log_file->file == nullptr) {
        perror("Error opening log_file file");
        return false;
    }
    return true;
}
References LogFileData::file, LogFileData::filename, and log_file.
Referenced by main(), and stk_log_printf().
stk_log_printf()
int stk_log_printf (LogFileData * log, const char * format, ...)
Prints data in printf format to log file.
Parameters
log
format
...
Returns
int
Definition at line 3 of file log.cpp.
                                                                   {
    assert(log_file);
    assert(format);
    bool file_is_opened_here = false;
    if (log_file->file == nullptr) {
        if (!stk_log_open_file(log_file))
            return -1;
        file_is_opened_here = true;
    }
    va_list arg_list = {};
    va_start(arg_list, format);
    int ret = vfprintf(log_file->file, format, arg_list);
    if (file_is_opened_here)
        if (!stk_log_close_file(log_file))
            return -1;
    return ret;
}
References LogFileData::file, log_file, stk_log_close_file(), and stk_log_open_file().
Referenced by stk_dump(), stk_print_error(), test_stack_error(), and test_stack_normal().