src/stack.cpp File Reference
#include stack.h
Macros
#define PRINT_ERR_(code, descr)
#define CHECK_ERR_(clause, err) if (clause) res |= err
Functions
int stk_ctor_debug (Stack *stk, const VarCodeData var_data, const size_t min_capacity)
Stack constructor in debug mode (calls stk_ctor() inside)
int stk_ctor (Stack *stk, const size_t min_capacity)
Stack constructor.
int stk_dtor (Stack *stk)
Stack destructor.
int stk_resize (Stack *stk)
Resizes stack.
int stk_push (Stack *stk, const Elem_t elem)
Pushes elem to stack.
int stk_pop (Stack *stk, Elem_t *const elem)
Pops elem from stack.
void stk_print_error (const int err_code)
Prints errors to log file.
void stk_dump (const Stack *stk, const VarCodeData call_data)
Dumps all stack data to log.
int stk_verify (Stack *stk)
Verifies stack.
Variables
LogFileData log_file
Macro Definition Documentation
CHECK_ERR_
#define CHECK_ERR_(clause, err) if (clause) res |= err
Definition at line 300 of file stack.cpp.
PRINT_ERR_
#define PRINT_ERR_(code, descr)
Value:
                                    if ((err_code) & Stack::code) \
                                    log_printf(&log_file, \
                                               HTML_TEXT(HTML_RED("!!! " #code ": " descr "\n")));
Definition at line 194 of file stack.cpp.
Function Documentation
stk_ctor()
int stk_ctor (Stack * stk, const size_t min_capacity = Stack::DEFAULT_CAPACITY)
Stack constructor.
Attention
Use with macros STK_CTOR or STK_CTOR_CAP
Parameters
stk
min_capacity
Returns
int
Definition at line 17 of file stack.cpp.
                                                    {
    assert(stk);
    int res = stk->OK;
    if (stk_is_initialised(stk)) {
        res |= stk->ALREADY_INITIALISED;
        STK_OK(stk, res);
        return res;
    }
    if (min_capacity == 0) {
        res |= stk->INVALID_MIN_CAPACITY;
        STK_OK(stk, res);
        return res;
    }
    stk->min_capacity = min_capacity;
    stk->data = (Elem_t*)calloc(calc_stk_data_size(stk->min_capacity), 1);
    if (stk->data == nullptr) {
        res |= stk->ALLOC_ERR;
        STK_OK(stk, res);
        return res;
    }
    stk->capacity = stk->min_capacity;
    stk->size = 0;
#ifdef CANARY_PROTECT
    stk->data = (Elem_t*)(((Canary_t*)stk->data) + 1);
     *left_data_canary_ptr(stk) = CANARY_VAL;
    *right_data_canary_ptr(stk) = CANARY_VAL;
#endif // #ifdef CANARY_PROTECT
    STK_FILL_POISON(stk, 0, stk->capacity);
#ifdef HASH_PROTECT
    stk->data_hash = stk_data_hash_calc(stk);
    stk->struct_hash = stk_struct_hash_calc(stk);
#endif // #ifdef HASH_PROTECT
    res |= STK_VERIFY(stk);
    STK_OK(stk, res);
    return res;
}
References Stack::ALLOC_ERR, Stack::ALREADY_INITIALISED, calc_stk_data_size(), Stack::capacity, Stack::data, Stack::data_hash, Stack::INVALID_MIN_CAPACITY, left_data_canary_ptr(), Stack::min_capacity, Stack::OK, right_data_canary_ptr(), Stack::size, stk_data_hash_calc(), STK_FILL_POISON, stk_is_initialised(), STK_OK, stk_struct_hash_calc(), STK_VERIFY, and Stack::struct_hash.
Referenced by stk_ctor_debug().
stk_ctor_debug()
int stk_ctor_debug (Stack * stk, const VarCodeData var_data, const size_t min_capacity = Stack::DEFAULT_CAPACITY)
Stack constructor in debug mode (calls stk_ctor() inside)
Parameters
stk
var_data initialising place
min_capacity
Returns
int
Definition at line 6 of file stack.cpp.
                                                                                      {
    assert(stk);
    stk->var_data = var_data;
    return stk_ctor(stk, min_capacity);
}
References stk_ctor(), and Stack::var_data.
stk_dtor()
int stk_dtor (Stack * stk)
Stack destructor.
Parameters
stk
Returns
int
Definition at line 69 of file stack.cpp.
                         {
    assert(stk);
    int res = STK_VERIFY(stk);
    STK_OK(stk, res);
    STK_FILL_POISON(stk, 0, stk->capacity);
#ifdef CANARY_PROTECT
    free((Canary_t*)stk->data - 1);
    stk->data = nullptr;
#else // #ifndef CANARY_PROTECT
    FREE(stk->data);
#endif // #ifdef CANARY_PROTECT
    stk->capacity = stk->UNITIALISED_CAPACITY;
    stk->size = stk->UNITIALISED_CAPACITY;
#ifdef HASH_PRTOTECT
    stk->struct_hash = 0;
    stk->data_hash = 0;
#endif // #ifdef HASH_PROTECT
    return res;
}
References Stack::capacity, Stack::data, Stack::data_hash, FREE, Stack::size, STK_FILL_POISON, STK_OK, STK_VERIFY, Stack::struct_hash, and Stack::UNITIALISED_CAPACITY.
Referenced by test_stack_error(), and test_stack_normal().
stk_dump()
void stk_dump (const Stack * stk, const VarCodeData call_data)
Dumps all stack data to log.
Parameters
stk
call_data
Definition at line 226 of file stack.cpp.
                                                             {
    assert(stk);
    log_printf(&log_file, HTML_BEGIN);
    log_printf(&log_file, " stk_dump() called from %s:%d %s\n"
                          " %s[%p] initialised in %s:%d %s \n",
                          call_data.file, call_data.line, call_data.func,
                          stk->var_data.name, stk,
                          stk->var_data.file, stk->var_data.line, stk->var_data.func);
    log_printf(&log_file, " {\n");
#ifdef CANARY_PROTECT
    log_printf(&log_file, " L_canary = 0x" CANARY_T_PRINTF "\n", stk->canary_left);
    log_printf(&log_file, " R_canary = 0x" CANARY_T_PRINTF "\n", stk->canary_right);
#endif // #ifdef CANARY_PROTECT
    log_printf(&log_file, " size = %zd\n"
                          " capacity = %zd\n"
                          " min capacity = %zu\n", stk->size, stk->capacity, stk->min_capacity);
#ifdef HASH_PROTECT
    log_printf(&log_file, " struct hash = 0x%X\n"
                          " data hash = 0x%X\n", stk->struct_hash, stk->data_hash);
#endif // #ifdef HASH_PROTECT
    log_printf(&log_file, " data[%p] {\n", stk->data);
    if (!is_ptr_valid(stk->data)) {
        if (stk_is_initialised(stk))
            log_printf(&log_file, HTML_RED(" can't read (invalid pointer)\n"));
        log_printf(&log_file, " }\n"
                              " }\n" HTML_END);
        return;
    }
#ifdef CANARY_PROTECT
    log_printf(&log_file, " L_canary = 0x" CANARY_T_PRINTF "\n",
               *left_data_canary_ptr(stk));
#endif // #ifdef CANARY_PROTECT
    int index_len = 1;
    ssize_t index = MAX(stk->size, stk->capacity);
    while ((index /= 10) > 0)
        index_len++;
    for (ssize_t i = 0; i < stk->capacity; i++) {
        if (i < stk->size)
            log_printf(&log_file, " *");
        else
            log_printf(&log_file, " ");
        log_printf(&log_file, "[%*zu] ", index_len, i);
        if (stk->data[i] == stk->POISON)
            log_printf(&log_file, "(poison)\n");
        else
            log_printf(&log_file, ELEM_T_PRINTF "\n", stk->data[i]);
    }
#ifdef CANARY_PROTECT
    log_printf(&log_file, " R_canary = 0x" CANARY_T_PRINTF "\n",
               *right_data_canary_ptr(stk));
#endif // #ifdef CANARY_PROTECT
    log_printf(&log_file, " }\n");
    log_printf(&log_file, " }\n");
}
References Stack::canary_left, Stack::canary_right, CANARY_T_PRINTF, Stack::capacity, Stack::data, Stack::data_hash, ELEM_T_PRINTF, VarCodeData::file, VarCodeData::func, HTML_BEGIN, HTML_END, HTML_RED, is_ptr_valid(), left_data_canary_ptr(), VarCodeData::line, log_file, log_printf(), MAX, Stack::min_capacity, VarCodeData::name, Stack::POISON, right_data_canary_ptr(), Stack::size, stk_is_initialised(), Stack::struct_hash, and Stack::var_data.
stk_pop()
int stk_pop (Stack * stk, Elem_t *const res)
Pops elem from stack.
Parameters
stk
res
Returns
int
Definition at line 164 of file stack.cpp.
                                            {
    assert(elem);
    int res = STK_ASSERT(stk);
    if (stk->size <= 0) {
        res |= stk->NOTHING_TO_POP;
        STK_OK(stk, res);
        return res;
    }
    *elem = stk->data[--stk->size];
#ifdef HASH_PROTECT
    stk->data_hash = stk_data_hash_calc(stk);
    stk->struct_hash = stk_struct_hash_calc(stk);
#endif // #ifdef HASH_PROTECT
    ON_DEBUG(stk->data[stk->size] = stk->POISON);
    res |= stk_resize(stk);
    res |= STK_VERIFY(stk);
    STK_OK(stk, res);
    return res;
}
References Stack::data, Stack::data_hash, Stack::NOTHING_TO_POP, ON_DEBUG, Stack::POISON, Stack::size, STK_ASSERT, stk_data_hash_calc(), STK_OK, stk_resize(), stk_struct_hash_calc(), STK_VERIFY, and Stack::struct_hash.
Referenced by test_stack_error(), and test_stack_normal().
stk_print_error()
void stk_print_error (const int err_code)
Prints errors to log file.
Parameters
err_code
Definition at line 198 of file stack.cpp.
                                         {
    if (err_code == Stack::OK) {
        log_printf(&log_file, HTML_TEXT(HTML_GREEN("No error\n")));
    } else {
        PRINT_ERR_(ALREADY_INITIALISED, "Constructor called for already initialised or corrupted stack");
        PRINT_ERR_(UNITIALISED, "Stack is not initialised");
        PRINT_ERR_(DATA_INVALID_PTR, "stk.data pointer is not valid for writing");
        PRINT_ERR_(ALLOC_ERR, "Can't allocate memory");
        PRINT_ERR_(NOTHING_TO_POP, "Program is trying to pop empty stack");
        PRINT_ERR_(POISON_VAL_FOUND, "There is poison value in stack");
        PRINT_ERR_(NON_POISON_EMPTY, "Empty element is not poison");
        PRINT_ERR_(STRUCT_HASH_ERR, "Stack struct was modified (wrong hash)");
        PRINT_ERR_(DATA_HASH_ERR, "Stack data was modified (wrong hash)");
        PRINT_ERR_(LOW_CAPACITY, "stk.size > stk.capacity");
        PRINT_ERR_(NEGATIVE_CAPACITY, "Negative stk.capacity");
        PRINT_ERR_(INVALID_MIN_CAPACITY, "Invalid min capacity given");
        PRINT_ERR_(NEGATIVE_SIZE, "Negative stk.size");
        PRINT_ERR_(STRUCT_L_CANARY_ERR, "Left struct canary is corrupt");
        PRINT_ERR_(STRUCT_R_CANARY_ERR, "Right struct canary is corrupt");
        PRINT_ERR_(DATA_L_CANARY_ERR, "Left data canary is corrupt");
        PRINT_ERR_(DATA_R_CANARY_ERR, "Right data canary is corrupt");
    }
}
References HTML_GREEN, HTML_TEXT, log_file, log_printf(), Stack::OK, and PRINT_ERR_.
stk_push()
int stk_push (Stack * stk, const Elem_t elem)
Pushes elem to stack.
Parameters
stk
elem
Returns
int
Definition at line 141 of file stack.cpp.
                                            {
    int res = STK_ASSERT(stk);
    res |= stk_resize(stk);
    if (res != stk->OK)
        return res;
    stk->data[stk->size++] = elem;
#ifdef HASH_PROTECT
    stk->data_hash = stk_data_hash_push(stk, stk->data[stk->size - 1], stk->data_hash);
    stk->struct_hash = stk_struct_hash_calc(stk);
#endif // #ifdef HASH_PROTECT
    res |= STK_VERIFY(stk);
    STK_OK(stk, res);
    return res;
}
References Stack::data, Stack::data_hash, Stack::OK, Stack::size, STK_ASSERT, stk_data_hash_push(), STK_OK, stk_resize(), stk_struct_hash_calc(), STK_VERIFY, and Stack::struct_hash.
Referenced by test_stack_error(), and test_stack_normal().
stk_resize()
int stk_resize (Stack * stk)
Resizes stack.
Parameters
stk
Returns
int
Definition at line 97 of file stack.cpp.
                           {
    int res = STK_ASSERT(stk);
    ssize_t new_size = stk->capacity;
    if (stk->size >= stk->capacity)
        new_size = stk->capacity * 2;
    else if (stk->size * 4 <= stk->capacity && stk->capacity >= (ssize_t)stk->min_capacity * 2)
        new_size = stk->capacity / 2;
    else
        return res;
    Elem_t* tmp = stk->data;
    stk->data = (Elem_t*)recalloc((void*)((Canary_t*)stk->data - 1),
             // We need to clear right canary and free space before it -> + 1
                         stk->capacity * sizeof(Elem_t) ON_CANARY_PROTECT(+ 1 * sizeof(CANARY_VAL)),
                         calc_stk_data_size(new_size));
    if (!stk->data) {
        stk->data = tmp;
        res |= stk->ALLOC_ERR;
        STK_OK(stk, res);
        return res;
    }
    ON_CANARY_PROTECT(stk->data = (Elem_t*)((Canary_t*)stk->data + 1));
    STK_FILL_POISON(stk, stk->capacity, new_size);
    stk->capacity = new_size;
    ON_CANARY_PROTECT(*right_data_canary_ptr(stk) = CANARY_VAL);
    ON_HASH_PROTECT(stk->struct_hash = stk_struct_hash_calc(stk));
    res |= STK_VERIFY(stk);
    STK_OK(stk, res);
    return res;
}
References Stack::ALLOC_ERR, calc_stk_data_size(), Stack::capacity, Stack::data, Stack::min_capacity, ON_CANARY_PROTECT, ON_HASH_PROTECT, recalloc(), right_data_canary_ptr(), Stack::size, STK_ASSERT, STK_FILL_POISON, STK_OK, stk_struct_hash_calc(), STK_VERIFY, and Stack::struct_hash.
Referenced by stk_pop(), and stk_push().
stk_verify()
int stk_verify (Stack * stk)
Verifies stack.
Parameters
stk
Returns
int error code
Definition at line 301 of file stack.cpp.
                           {
    assert(stk);
    int res = stk->OK;
    if (!stk_is_initialised(stk)) {
        res |= stk->UNITIALISED;
        return res;
    }
    bool is_data_valid = true;
    if (!is_ptr_valid(stk->data, 'w')) {
        res |= stk->DATA_INVALID_PTR;
        is_data_valid = false;
    }
    if (is_data_valid)
        for (ssize_t i = 0; i < stk->size; i++)
            if (stk->data[i] == stk->POISON) {
                res |= stk->POISON_VAL_FOUND;
                break;
            }
    if (is_data_valid)
        for (ssize_t i = stk->size; i < stk->capacity; i++)
            if (stk->data[i] != stk->POISON) {
                res |= stk->NON_POISON_EMPTY;
                break;
            }
#ifdef HASH_PROTECT
    CRC32_t tmp_struct_hash = stk->struct_hash;
    if (is_data_valid) {
        CRC32_t data_hash = stk_data_hash_calc(stk);
        CHECK_ERR_(stk->data_hash != data_hash, stk->DATA_HASH_ERR);
    }
    CRC32_t struct_hash = stk_struct_hash_calc(stk);
    stk->struct_hash = tmp_struct_hash;
    CHECK_ERR_(stk->struct_hash != struct_hash, stk->STRUCT_HASH_ERR);
#endif // #ifdef HASH_PROTECT
    CHECK_ERR_(stk->capacity < stk->size, stk->LOW_CAPACITY);
    CHECK_ERR_(stk->capacity < 0, stk->NEGATIVE_CAPACITY);
    CHECK_ERR_(stk->min_capacity == 0, stk->INVALID_MIN_CAPACITY);
    CHECK_ERR_(stk->size < 0, stk->NEGATIVE_SIZE);
#ifdef CANARY_PROTECT
    CHECK_ERR_(stk->canary_left != CANARY_VAL, stk->STRUCT_L_CANARY_ERR);
    CHECK_ERR_(stk->canary_right != CANARY_VAL, stk->STRUCT_R_CANARY_ERR);
    if (is_data_valid) {
        CHECK_ERR_(*left_data_canary_ptr(stk) != CANARY_VAL, stk->DATA_L_CANARY_ERR);
        CHECK_ERR_(*right_data_canary_ptr(stk) != CANARY_VAL, stk->DATA_R_CANARY_ERR);
    }
#endif // #ifdef CANARY_PROTECT
    return res;
}
References Stack::canary_left, Stack::canary_right, Stack::capacity, CHECK_ERR_, Stack::data, Stack::data_hash, Stack::DATA_HASH_ERR, Stack::DATA_INVALID_PTR, Stack::DATA_L_CANARY_ERR, Stack::DATA_R_CANARY_ERR, Stack::INVALID_MIN_CAPACITY, is_ptr_valid(), left_data_canary_ptr(), Stack::LOW_CAPACITY, Stack::min_capacity, Stack::NEGATIVE_CAPACITY, Stack::NEGATIVE_SIZE, Stack::NON_POISON_EMPTY, Stack::OK, Stack::POISON, Stack::POISON_VAL_FOUND, right_data_canary_ptr(), Stack::size, stk_data_hash_calc(), stk_is_initialised(), stk_struct_hash_calc(), Stack::struct_hash, Stack::STRUCT_HASH_ERR, Stack::STRUCT_L_CANARY_ERR, Stack::STRUCT_R_CANARY_ERR, and Stack::UNITIALISED.
Variable Documentation
log_file
LogFileData log_file [extern]
Definition at line 4 of file main.cpp.
Referenced by stk_dump(), and stk_print_error().