src/stack.h File Reference
#include <stdlib.h>
#include <assert.h>
#include <malloc.h>
#include <math.h>
#include "utils/html.h"
#include "utils/macros.h"
#include "hash/crc32.h"
#include "utils/ptr_valid.h"
Classes
struct Stack
Stack data struct.
Macros
#define DEBUG
#define CANARY_PROTECT
#define HASH_PROTECT
#define ELEM_T_PRINTF "%d"
#define CANARY_T_PRINTF "%llX"
#define ON_DEBUG(...) __VA_ARGS__
hidden ifdef macros for DEBUG
#define STK_CTOR(stk) stk_ctor_debug(stk, VAR_CODE_DATA_PTR(stk))
stk_ctor macros
#define STK_CTOR_CAP(stk, capacity) stk_ctor_debug(stk, VAR_CODE_DATA_PTR(stk), capacity)
stk_ctor macros with capacity
#define STK_ASSERT(stk)
Used in the beginning of stk_ function.
#define STK_FILL_POISON(stk, begin, end)
fills stk data array with poison
#define STK_VERIFY(stk) stk_verify(stk)
stk_verify() enables in DEBUG mode
#define STK_OK(stk, res)
calls stk_print_error() and STK_DUMP() if stack is not OK
#define STK_DUMP(stk) stk_dump(stk, VAR_CODE_DATA())
stk_dump macros
#define ON_HASH_PROTECT(...) __VA_ARGS__
hidden ifdef macros for HASH_PROTECT
#define ON_CANARY_PROTECT(...) __VA_ARGS__
hidden ifdef macros for CANARY_PROTECT
Typedefs
typedef signed char Elem_t
typedef unsigned long long Canary_t
Functions
int stk_ctor (Stack *stk, const size_t init_capacity=Stack::DEFAULT_CAPACITY)
Stack constructor.
bool stk_is_initialised (const Stack *stk)
Checks if stack is initialised.
int stk_push (Stack *stk, const Elem_t elem)
Pushes elem to stack.
int stk_pop (Stack *stk, Elem_t *const res)
Pops elem from stack.
int stk_resize (Stack *stk, const size_t new_size)
Resizes stack.
int stk_dtor (Stack *stk)
Stack destructor.
int stk_ctor_debug (Stack *stk, const VarCodeData var_data, const size_t min_capacity=Stack::DEFAULT_CAPACITY)
Stack constructor in debug mode (calls stk_ctor() inside)
void stk_dump (const Stack *stk, const VarCodeData call_data)
Dumps all stack data to log.
int stk_verify (Stack *stk)
Verifies stack.
void stk_print_error (const int err_code)
Prints errors to log file.
CRC32_t stk_struct_hash_calc (Stack *stk)
Calculates hash for Stack struct.
CRC32_t stk_data_hash_calc (Stack *stk)
Calculates hash for stk.data.
CRC32_t stk_data_hash_push (Stack *stk, Elem_t elem, CRC32_t crc)
Addes one elemnt to stk.data hash.
Canary_t * left_data_canary_ptr (const Stack *stk)
Returns pointer to stk.data left canary.
Canary_t * right_data_canary_ptr (const Stack *stk)
Returns pointer to stk.data right canary.
int stk_resize_up (Stack *stk)
Calcs new stk size, when size is rising and does resize.
int stk_resize_down (Stack *stk)
Calcs new stk size, when size is falling and does resize.
size_t calc_stk_data_size (size_t len)
Calcs stk.data size in bytes.
Macro Definition Documentation
CANARY_PROTECT
#define CANARY_PROTECT
Definition at line 14 of file stack.h.
CANARY_T_PRINTF
#define CANARY_T_PRINTF "%llX"
Definition at line 24 of file stack.h.
DEBUG
#define DEBUG
Definition at line 13 of file stack.h.
ELEM_T_PRINTF
#define ELEM_T_PRINTF "%d"
Definition at line 20 of file stack.h.
HASH_PROTECT
#define HASH_PROTECT
Definition at line 15 of file stack.h.
ON_CANARY_PROTECT
#define ON_CANARY_PROTECT(...) __VA_ARGS__
hidden ifdef macros for CANARY_PROTECT
Definition at line 325 of file stack.h.
ON_DEBUG
#define ON_DEBUG(...) __VA_ARGS__
hidden ifdef macros for DEBUG
Definition at line 148 of file stack.h.
ON_HASH_PROTECT
#define ON_HASH_PROTECT(...) __VA_ARGS__
hidden ifdef macros for HASH_PROTECT
Definition at line 271 of file stack.h.
STK_ASSERT
#define STK_ASSERT(stk)
Value:
        STK_VERIFY(stk); \
        STK_OK(stk, res); \
                            \
        if (res != stk->OK) \
            return res
Used in the beginning of stk_ function.
Definition at line 197 of file stack.h.
                                   { \
                                    if (res != stk->OK) { \
                                        stk_print_error(res); \
                                        STK_DUMP(stk); \
                                    } \
                                } while (0)
    #define STK_DUMP(stk) stk_dump(stk, VAR_CODE_DATA())
#else // #ifndef DEBUG
    #define ON_DEBUG(...)
    #define STK_CTOR(stk) stk_ctor(stk)
    #define STK_CTOR_CAP(stk, capacity) stk_ctor(stk, capacity)
    #define STK_ASSERT(stk) Stack::OK
    #define STK_FILL_POISON(stk, begin, end) void (0)
    #define STK_VERIFY(stk) Stack::OK;
    #define STK_OK(stk, res) void (0)
    #define STK_DUMP(stk) void (0)
#endif // #ifdef DEBUG
#ifdef HASH_PROTECT
#define ON_HASH_PROTECT(...) __VA_ARGS__
inline CRC32_t stk_struct_hash_calc(Stack* stk) {
    assert(stk);
    stk->struct_hash = 0;
    return crc_add(0, (char*)stk, sizeof(stk));
}
inline CRC32_t stk_data_hash_calc(Stack* stk) {
    assert(stk);
    return crc_add(0, (char*)stk->data, sizeof(Elem_t) * stk->size);
}
inline CRC32_t stk_data_hash_push(Stack* stk, Elem_t elem, CRC32_t crc) {
    assert(stk);
    return crc_add(crc, (char*)(&elem), sizeof(elem));
}
#else // #ifndef HASH_PROTECT
#define ON_HASH_PROTECT(...)
#endif // #ifdef HASH_PROTECT
#ifdef CANARY_PROTECT
#define ON_CANARY_PROTECT(...) __VA_ARGS__
inline Canary_t* left_data_canary_ptr(const Stack* stk) {
    assert(stk);
    assert(stk->data);
    return (Canary_t*)stk->data - 1;
}
inline Canary_t* right_data_canary_ptr(const Stack* stk) {
    assert(stk);
    assert(stk->data);
    return (Canary_t*)((char*)stk->data + stk->capacity * sizeof(Elem_t)
                     + sizeof(Canary_t) - stk->capacity * sizeof(Elem_t) % sizeof(Canary_t));
}
#else // #ifndef CANARY_PROTECT
#define ON_CANARY_PROTECT(...)
#endif // #ifdef CANARY_PROTECT
inline int stk_resize_up(Stack* stk) {
    int res = STK_ASSERT(stk);
    ssize_t new_cap = stk->capacity;
    while (stk->size >= new_cap)
        new_cap *= 2;
    if (new_cap != stk->capacity)
        return res | stk_resize(stk, new_cap);
    return res;
}
inline int stk_resize_down(Stack* stk) {
    int res = STK_ASSERT(stk);
    ssize_t new_cap = stk->capacity;
    if (stk->size * 4 <= new_cap && new_cap >= (ssize_t)stk->DEFAULT_CAPACITY * 2)
        new_cap /= 2;
    if (new_cap != stk->capacity)
        return res | stk_resize(stk, new_cap);
    return res;
}
inline size_t calc_stk_data_size(size_t len) {
    return len * sizeof(Elem_t)
           ON_CANARY_PROTECT(+ sizeof(Canary_t) - len * sizeof(Elem_t) % sizeof(Canary_t)
                             + 2 * sizeof(Canary_t));
}
#endif // #ifndef STACK_H_
STK_CTOR
#define STK_CTOR(stk) stk_ctor_debug(stk, VAR_CODE_DATA_PTR(stk))
stk_ctor macros
Definition at line 153 of file stack.h.
STK_CTOR_CAP
#define STK_CTOR_CAP(stk, capacity) stk_ctor_debug(stk, VAR_CODE_DATA_PTR(stk), capacity)
stk_ctor macros with capacity
Definition at line 158 of file stack.h.
STK_DUMP
#define STK_DUMP(stk) stk_dump(stk, VAR_CODE_DATA())
stk_dump macros
Definition at line 229 of file stack.h.
STK_FILL_POISON
#define STK_FILL_POISON(stk, begin, end)
Value:
                if (end > begin) \
                    fill(stk->data + begin, end - begin, &stk->POISON, sizeof(Elem_t))
fills stk data array with poison
Definition at line 207 of file stack.h.
STK_OK
#define STK_OK(stk, res)
Value:
                                    do { \
                                    if (res != stk->OK) { \
                                        stk_print_error(res); \
                                        STK_DUMP(stk); \
                                    } \
                                } while (0)
calls stk_print_error() and STK_DUMP() if stack is not OK
Definition at line 219 of file stack.h.
                                   { \
                                    if (res != stk->OK) { \
                                        stk_print_error(res); \
                                        STK_DUMP(stk); \
                                    } \
                                } while (0)
STK_VERIFY
#define STK_VERIFY(stk) stk_verify(stk)
stk_verify() enables in DEBUG mode
Definition at line 214 of file stack.h.
Typedef Documentation
Canary_t
typedef unsigned long long Canary_t
Definition at line 22 of file stack.h.
Elem_t
typedef signed char Elem_t
Definition at line 18 of file stack.h.
Function Documentation
calc_stk_data_size()
size_t calc_stk_data_size (size_t len) [inline]
Calcs stk.data size in bytes.
Parameters
len data array len
Returns
size_t
Definition at line 409 of file stack.h.
                                             {
    return len * sizeof(Elem_t)
           ON_CANARY_PROTECT(+ sizeof(Canary_t) - len * sizeof(Elem_t) % sizeof(Canary_t)
                             + 2 * sizeof(Canary_t));
}
References ON_CANARY_PROTECT.
Referenced by stk_ctor(), and stk_resize().
left_data_canary_ptr()
Canary_t * left_data_canary_ptr (const Stack * stk) [inline]
Returns pointer to stk.data left canary.
Parameters
stk
Returns
Canary_t*
Definition at line 333 of file stack.h.
                                                        {
    assert(stk);
    assert(stk->data);
    return (Canary_t*)stk->data - 1;
}
References Stack::data.
Referenced by stk_ctor(), stk_dump(), and stk_verify().
right_data_canary_ptr()
Canary_t * right_data_canary_ptr (const Stack * stk) [inline]
Returns pointer to stk.data right canary.
Parameters
stk
Returns
Canary_t*
Definition at line 346 of file stack.h.
                                                         {
    assert(stk);
    assert(stk->data);
    return (Canary_t*)((char*)stk->data + stk->capacity * sizeof(Elem_t)
                     + sizeof(Canary_t) - stk->capacity * sizeof(Elem_t) % sizeof(Canary_t));
}
References Stack::capacity, and Stack::data.
Referenced by stk_ctor(), stk_dump(), stk_resize(), and stk_verify().
stk_ctor()
int stk_ctor (Stack * stk, const size_t init_capacity = Stack::DEFAULT_CAPACITY)
Stack constructor.
Attention
Use with macros STK_CTOR or STK_CTOR_CAP
Parameters
stk
init_capacity
Returns
int
Definition at line 27 of file stack.cpp.
                                                     {
    assert(stk);
    int res = stk->OK;
    if (stk_is_initialised(stk)) {
        res |= stk->ALREADY_INITIALISED;
        STK_OK(stk, res);
        return res;
    }
    if (init_capacity == 0) {
        res |= stk->INVALID_CAPACITY;
        STK_OK(stk, res);
        return res;
    }
    stk->data = (Elem_t*)calloc(calc_stk_data_size(init_capacity), 1);
    if (stk->data == nullptr) {
        res |= stk->ALLOC_ERR;
        STK_OK(stk, res);
        return res;
    }
    stk->capacity = init_capacity;
    stk->size = 0;
#ifdef CANARY_PROTECT
    stk->data = (Elem_t*)(((Canary_t*)stk->data) + 1);
     *left_data_canary_ptr(stk) = CANARY_VAL;
    *right_data_canary_ptr(stk) = CANARY_VAL;
#endif //< #ifdef CANARY_PROTECT
    STK_FILL_POISON(stk, 0, stk->capacity);
#ifdef HASH_PROTECT
    stk->data_hash = stk_data_hash_calc(stk);
    stk->struct_hash = stk_struct_hash_calc(stk);
#endif //< #ifdef HASH_PROTECT
    res |= STK_VERIFY(stk);
    STK_OK(stk, res);
    return res;
}
References Stack::ALLOC_ERR, Stack::ALREADY_INITIALISED, calc_stk_data_size(), Stack::capacity, Stack::data, Stack::data_hash, Stack::INVALID_CAPACITY, left_data_canary_ptr(), Stack::OK, right_data_canary_ptr(), Stack::size, stk_data_hash_calc(), STK_FILL_POISON, stk_is_initialised(), STK_OK, stk_struct_hash_calc(), STK_VERIFY, and Stack::struct_hash.
Referenced by stk_ctor_debug().
stk_ctor_debug()
int stk_ctor_debug (Stack * stk, const VarCodeData var_data, const size_t min_capacity = Stack::DEFAULT_CAPACITY)
Stack constructor in debug mode (calls stk_ctor() inside)
Parameters
stk
var_data initialising place
min_capacity
Returns
int
Definition at line 16 of file stack.cpp.
                                                                                      {
    assert(stk);
    stk->var_data = var_data;
    return stk_ctor(stk, min_capacity);
}
References stk_ctor(), and Stack::var_data.
stk_data_hash_calc()
CRC32_t stk_data_hash_calc (Stack * stk) [inline]
Calculates hash for stk.data.
Parameters
stk
Returns
CRC32_t
Definition at line 292 of file stack.h.
                                              {
    assert(stk);
    return crc_add(0, (char*)stk->data, sizeof(Elem_t) * stk->size);
}
References crc_add(), Stack::data, and Stack::size.
Referenced by stk_ctor(), stk_pop(), and stk_verify().
stk_data_hash_push()
CRC32_t stk_data_hash_push (Stack * stk, Elem_t elem, CRC32_t crc) [inline]
Addes one elemnt to stk.data hash.
Parameters
stk
elem
crc
Returns
CRC32_t
Definition at line 306 of file stack.h.
                                                                        {
    assert(stk);
    return crc_add(crc, (char*)(&elem), sizeof(elem));
}
References crc_add().
Referenced by stk_push().
stk_dtor()
int stk_dtor (Stack * stk)
Stack destructor.
Parameters
stk
Returns
int
Definition at line 77 of file stack.cpp.
                         {
    assert(stk);
    int res = STK_VERIFY(stk);
    STK_OK(stk, res);
    STK_FILL_POISON(stk, 0, stk->capacity);
#ifdef CANARY_PROTECT
    free((Canary_t*)stk->data - 1);
    stk->data = nullptr;
#else //< #ifndef CANARY_PROTECT
    FREE(stk->data);
#endif //< #ifdef CANARY_PROTECT
    stk->capacity = stk->UNITIALISED_CAPACITY;
    stk->size = stk->UNITIALISED_CAPACITY;
#ifdef HASH_PROTECT
    stk->struct_hash = 0;
    stk->data_hash = 0;
#endif //< #ifdef HASH_PROTECT
    return res;
}
References Stack::capacity, Stack::data, Stack::data_hash, FREE, Stack::size, STK_FILL_POISON, STK_OK, STK_VERIFY, Stack::struct_hash, and Stack::UNITIALISED_CAPACITY.
Referenced by test_stack_error(), and test_stack_normal().
stk_dump()
void stk_dump (const Stack * stk, const VarCodeData call_data)
Dumps all stack data to log.
Parameters
stk
call_data
Definition at line 235 of file stack.cpp.
                                                             {
    assert(stk);
    stk_log_printf(&log_file, HTML_BEGIN);
    stk_log_printf(&log_file, " stk_dump() called from %s:%d %s\n"
                          " %s[%p] initialised in %s:%d %s \n",
                          call_data.file, call_data.line, call_data.func,
                          stk->var_data.name, stk,
                          stk->var_data.file, stk->var_data.line, stk->var_data.func);
    stk_log_printf(&log_file, " {\n");
#ifdef CANARY_PROTECT
    stk_log_printf(&log_file, " L_canary = 0x" CANARY_T_PRINTF "\n", stk->canary_left);
    stk_log_printf(&log_file, " R_canary = 0x" CANARY_T_PRINTF "\n", stk->canary_right);
#endif //< #ifdef CANARY_PROTECT
    stk_log_printf(&log_file, " size = %zd\n"
                          " capacity = %zd\n", stk->size, stk->capacity);
#ifdef HASH_PROTECT
    stk_log_printf(&log_file, " struct hash = 0x%X\n"
                          " data hash = 0x%X\n", stk->struct_hash, stk->data_hash);
#endif //< #ifdef HASH_PROTECT
    stk_log_printf(&log_file, " data[%p] {\n", stk->data);
    if (!is_ptr_valid(stk->data)) {
        if (stk_is_initialised(stk))
            stk_log_printf(&log_file, HTML_RED(" can't read (invalid pointer)\n"));
        stk_log_printf(&log_file, " }\n"
                              " }\n" HTML_END);
        return;
    }
#ifdef CANARY_PROTECT
    stk_log_printf(&log_file, " L_canary = 0x" CANARY_T_PRINTF "\n",
               *left_data_canary_ptr(stk));
#endif //< #ifdef CANARY_PROTECT
    int index_len = 1;
    ssize_t index = MAX(stk->size, stk->capacity);
    while ((index /= 10) > 0)
        index_len++;
    for (ssize_t i = 0; i < stk->capacity; i++) {
        if (i < stk->size)
            stk_log_printf(&log_file, " *");
        else
            stk_log_printf(&log_file, " ");
        stk_log_printf(&log_file, "[%*zu] ", index_len, i);
        if (stk->data[i] == stk->POISON)
            stk_log_printf(&log_file, "(poison)\n");
        else
            stk_log_printf(&log_file, ELEM_T_PRINTF "\n", stk->data[i]);
    }
#ifdef CANARY_PROTECT
    stk_log_printf(&log_file, " R_canary = 0x" CANARY_T_PRINTF "\n",
               *right_data_canary_ptr(stk));
#endif //< #ifdef CANARY_PROTECT
    stk_log_printf(&log_file, " }\n");
    stk_log_printf(&log_file, " }\n" HTML_END);
}
References Stack::canary_left, Stack::canary_right, CANARY_T_PRINTF, Stack::capacity, Stack::data, Stack::data_hash, ELEM_T_PRINTF, VarCodeData::file, VarCodeData::func, HTML_BEGIN, HTML_END, HTML_RED, is_ptr_valid(), left_data_canary_ptr(), VarCodeData::line, log_file, MAX, VarCodeData::name, Stack::POISON, right_data_canary_ptr(), Stack::size, stk_is_initialised(), stk_log_printf(), Stack::struct_hash, and Stack::var_data.
stk_is_initialised()
bool stk_is_initialised (const Stack * stk) [inline]
Checks if stack is initialised.
Parameters
stk
Returns
true
false
Definition at line 102 of file stack.h.
                                                 {
    return stk->size != stk->UNITIALISED_CAPACITY ||
           stk->capacity != stk->UNITIALISED_CAPACITY ||
           stk->data != nullptr;
}
References Stack::capacity, Stack::data, Stack::size, and Stack::UNITIALISED_CAPACITY.
Referenced by stk_ctor(), stk_dump(), and stk_verify().
stk_pop()
int stk_pop (Stack * stk, Elem_t *const res)
Pops elem from stack.
Parameters
stk
res
Returns
int
Definition at line 169 of file stack.cpp.
                                            {
    assert(elem);
    int res = STK_ASSERT(stk);
    if (stk->size <= 0) {
        res |= stk->NOTHING_TO_POP;
        STK_OK(stk, res);
        return res;
    }
    *elem = stk->data[--stk->size];
#ifdef HASH_PROTECT
    stk->data_hash = stk_data_hash_calc(stk);
    stk->struct_hash = stk_struct_hash_calc(stk);
#endif //< #ifdef HASH_PROTECT
    ON_DEBUG(stk->data[stk->size] = stk->POISON);
    res |= stk_resize_down(stk);
    res |= STK_VERIFY(stk);
    STK_OK(stk, res);
    return res;
}
References Stack::data, Stack::data_hash, Stack::NOTHING_TO_POP, ON_DEBUG, Stack::POISON, Stack::size, STK_ASSERT, stk_data_hash_calc(), STK_OK, stk_resize_down(), stk_struct_hash_calc(), STK_VERIFY, and Stack::struct_hash.
Referenced by test_stack_error(), and test_stack_normal().
stk_print_error()
void stk_print_error (const int err_code)
Prints errors to log file.
Parameters
err_code
Definition at line 205 of file stack.cpp.
                                         {
    if (err_code == Stack::OK) {
        stk_log_printf(&log_file, HTML_TEXT(HTML_GREEN("No error\n")));
    } else {
        PRINT_ERR_(ALREADY_INITIALISED, "Constructor called for already initialised or corrupted stack");
        PRINT_ERR_(UNITIALISED, "Stack is not initialised");
        PRINT_ERR_(DATA_INVALID_PTR, "stk.data pointer is not valid for writing");
        PRINT_ERR_(ALLOC_ERR, "Can't allocate memory");
        PRINT_ERR_(NOTHING_TO_POP, "Program is trying to pop empty stack");
        PRINT_ERR_(POISON_VAL_FOUND, "There is poison value in stack");
        PRINT_ERR_(NON_POISON_EMPTY, "Empty element is not poison");
        PRINT_ERR_(STRUCT_HASH_ERR, "Stack struct was modified (wrong hash)");
        PRINT_ERR_(DATA_HASH_ERR, "Stack data was modified (wrong hash)");
        PRINT_ERR_(LOW_CAPACITY, "stk.size > stk.capacity");
        PRINT_ERR_(NEGATIVE_CAPACITY, "Negative stk.capacity");
        PRINT_ERR_(INVALID_CAPACITY, "Invalid capacity given");
        PRINT_ERR_(NEGATIVE_SIZE, "Negative stk.size");
        PRINT_ERR_(STRUCT_L_CANARY_ERR, "Left struct canary is corrupt");
        PRINT_ERR_(STRUCT_R_CANARY_ERR, "Right struct canary is corrupt");
        PRINT_ERR_(DATA_L_CANARY_ERR, "Left data canary is corrupt");
        PRINT_ERR_(DATA_R_CANARY_ERR, "Right data canary is corrupt");
    }
}
References HTML_GREEN, HTML_TEXT, log_file, Stack::OK, PRINT_ERR_, and stk_log_printf().
stk_push()
int stk_push (Stack * stk, const Elem_t elem)
Pushes elem to stack.
Parameters
stk
elem
Returns
int
Definition at line 146 of file stack.cpp.
                                            {
    int res = STK_ASSERT(stk);
    res |= stk_resize_up(stk);
    if (res != stk->OK)
        return res;
    stk->data[stk->size++] = elem;
#ifdef HASH_PROTECT
    stk->data_hash = stk_data_hash_push(stk, stk->data[stk->size - 1], stk->data_hash);
    stk->struct_hash = stk_struct_hash_calc(stk);
#endif //< #ifdef HASH_PROTECT
    res |= STK_VERIFY(stk);
    STK_OK(stk, res);
    return res;
}
References Stack::data, Stack::data_hash, Stack::OK, Stack::size, STK_ASSERT, stk_data_hash_push(), STK_OK, stk_resize_up(), stk_struct_hash_calc(), STK_VERIFY, and Stack::struct_hash.
Referenced by test_stack_error(), and test_stack_normal().
stk_resize()
int stk_resize (Stack * stk, const size_t new_size)
Resizes stack.
Parameters
stk
new_size
Returns
int
Definition at line 105 of file stack.cpp.
                                            {
    int res = STK_ASSERT(stk);
    if (new_size == 0) {
        res |= stk->INVALID_CAPACITY;
        STK_OK(stk, res);
        return res;
    }
    Elem_t* tmp = stk->data;
    stk->data = (Elem_t*)recalloc((void*)((Canary_t*)stk->data ON_CANARY_PROTECT(- 1)),
             // We need to clear right canary and free space before it -> + 1
                         stk->capacity * sizeof(Elem_t) ON_CANARY_PROTECT(+ 1 * sizeof(CANARY_VAL)),
                         calc_stk_data_size(new_size));
    if (!stk->data) {
        stk->data = tmp;
        res |= stk->ALLOC_ERR;
        STK_OK(stk, res);
        return res;
    }
    ON_CANARY_PROTECT(stk->data = (Elem_t*)((Canary_t*)stk->data + 1));
    STK_FILL_POISON(stk, stk->capacity, (ssize_t)new_size);
    stk->capacity = new_size;
    ON_CANARY_PROTECT(*right_data_canary_ptr(stk) = CANARY_VAL);
    ON_HASH_PROTECT(stk->struct_hash = stk_struct_hash_calc(stk));
    res |= STK_VERIFY(stk);
    STK_OK(stk, res);
    return res;
}
References Stack::ALLOC_ERR, calc_stk_data_size(), Stack::capacity, Stack::data, Stack::INVALID_CAPACITY, ON_CANARY_PROTECT, ON_HASH_PROTECT, recalloc(), right_data_canary_ptr(), STK_ASSERT, STK_FILL_POISON, STK_OK, stk_struct_hash_calc(), STK_VERIFY, and Stack::struct_hash.
Referenced by stk_resize_down(), and stk_resize_up().
stk_resize_down()
int stk_resize_down (Stack * stk) [inline]
Calcs new stk size, when size is falling and does resize.
Parameters
stk
Returns
int
Definition at line 389 of file stack.h.
                                       {
    int res = STK_ASSERT(stk);
    ssize_t new_cap = stk->capacity;
    if (stk->size * 4 <= new_cap && new_cap >= (ssize_t)stk->DEFAULT_CAPACITY * 2)
        new_cap /= 2;
    if (new_cap != stk->capacity)
        return res | stk_resize(stk, new_cap);
    return res;
}
References Stack::capacity, Stack::DEFAULT_CAPACITY, Stack::size, STK_ASSERT, and stk_resize().
Referenced by stk_pop().
stk_resize_up()
int stk_resize_up (Stack * stk) [inline]
Calcs new stk size, when size is rising and does resize.
Parameters
stk
Returns
int
Definition at line 369 of file stack.h.
                                     {
    int res = STK_ASSERT(stk);
    ssize_t new_cap = stk->capacity;
    while (stk->size >= new_cap)
        new_cap *= 2;
    if (new_cap != stk->capacity)
        return res | stk_resize(stk, new_cap);
    return res;
}
References Stack::capacity, Stack::size, STK_ASSERT, and stk_resize().
Referenced by stk_push().
stk_struct_hash_calc()
CRC32_t stk_struct_hash_calc (Stack * stk) [inline]
Calculates hash for Stack struct.
Parameters
stk
Returns
CRC32_t
Definition at line 279 of file stack.h.
                                                {
    assert(stk);
    stk->struct_hash = 0;
    return crc_add(0, (char*)stk, sizeof(stk));
}
References crc_add(), and Stack::struct_hash.
Referenced by stk_ctor(), stk_pop(), stk_push(), stk_resize(), and stk_verify().
stk_verify()
int stk_verify (Stack * stk)
Verifies stack.
Parameters
stk
Returns
int error code
Definition at line 309 of file stack.cpp.
                           {
    assert(stk);
    int res = stk->OK;
    if (!stk_is_initialised(stk)) {
        res |= stk->UNITIALISED;
        return res;
    }
    bool is_data_valid = true;
    if (!is_ptr_valid(stk->data)) {
        res |= stk->DATA_INVALID_PTR;
        is_data_valid = false;
    }
    if (is_data_valid) {
        for (ssize_t i = 0; i < stk->size; i++)
            if (stk->data[i] == stk->POISON) {
                res |= stk->POISON_VAL_FOUND;
                break;
            }
        for (ssize_t i = stk->size; i < stk->capacity; i++)
            if (stk->data[i] != stk->POISON) {
                res |= stk->NON_POISON_EMPTY;
                break;
            }
    }
#ifdef HASH_PROTECT
    CRC32_t tmp_struct_hash = stk->struct_hash;
    if (is_data_valid) {
        CRC32_t data_hash = stk_data_hash_calc(stk);
        CHECK_ERR_(stk->data_hash != data_hash, stk->DATA_HASH_ERR);
    }
    CRC32_t struct_hash = stk_struct_hash_calc(stk);
    stk->struct_hash = tmp_struct_hash;
    CHECK_ERR_(stk->struct_hash != struct_hash, stk->STRUCT_HASH_ERR);
#endif //< #ifdef HASH_PROTECT
    CHECK_ERR_(stk->capacity < stk->size, stk->LOW_CAPACITY);
    CHECK_ERR_(stk->capacity < 0, stk->NEGATIVE_CAPACITY);
    CHECK_ERR_(stk->size < 0, stk->NEGATIVE_SIZE);
#ifdef CANARY_PROTECT
    CHECK_ERR_(stk->canary_left != CANARY_VAL, stk->STRUCT_L_CANARY_ERR);
    CHECK_ERR_(stk->canary_right != CANARY_VAL, stk->STRUCT_R_CANARY_ERR);
    if (is_data_valid) {
        CHECK_ERR_(*left_data_canary_ptr(stk) != CANARY_VAL, stk->DATA_L_CANARY_ERR);
        CHECK_ERR_(*right_data_canary_ptr(stk) != CANARY_VAL, stk->DATA_R_CANARY_ERR);
    }
#endif //< #ifdef CANARY_PROTECT
    return res;
}
References Stack::canary_left, Stack::canary_right, Stack::capacity, CHECK_ERR_, Stack::data, Stack::data_hash, Stack::DATA_HASH_ERR, Stack::DATA_INVALID_PTR, Stack::DATA_L_CANARY_ERR, Stack::DATA_R_CANARY_ERR, is_ptr_valid(), left_data_canary_ptr(), Stack::LOW_CAPACITY, Stack::NEGATIVE_CAPACITY, Stack::NEGATIVE_SIZE, Stack::NON_POISON_EMPTY, Stack::OK, Stack::POISON, Stack::POISON_VAL_FOUND, right_data_canary_ptr(), Stack::size, stk_data_hash_calc(), stk_is_initialised(), stk_struct_hash_calc(), Stack::struct_hash, Stack::STRUCT_HASH_ERR, Stack::STRUCT_L_CANARY_ERR, Stack::STRUCT_R_CANARY_ERR, and Stack::UNITIALISED.