src/test/test.cpp File Reference
#include test.h
Functions
void test_stack_normal ()
Tests stack without messing it up.
void test_stack_error ()
Tests stack by damaging it.
Function Documentation
test_stack_error()
void test_stack_error ()
Tests stack by damaging it.
incorrect stk.data usage test
reset stack
empty stack pop test
Definition at line 47 of file test.cpp.
                        {
    log_printf(&log_file, HTML_H2("---Test stack (error)---\n"));
    Stack stk = {};
    STK_CTOR(&stk);
    stk_push(&stk, 123);
    STK_DUMP(&stk);
    for (Elem_t i = 0; i < 10; i++)
        stk_push(&stk, i);
    STK_DUMP(&stk);
    stk.data[13] = 0;
    stk.data[5] = 111;
    stk_push(&stk, 1);
    STK_DUMP(&stk);
    stk_dtor(&stk);
    STK_CTOR(&stk);
    for (Elem_t i = 0; i < 10; i++)
        stk_push(&stk, i);
    for (Elem_t i = 0; i < 11; i++) {
        Elem_t p = 0;
        stk_pop(&stk, &p);
    }
    STK_DUMP(&stk);
    stk_dtor(&stk);
    STK_DUMP(&stk);
    log_printf(&log_file, HTML_H2("---Test stack (error) end---\n"));
}
References Stack::data, HTML_H2, log_file, log_printf(), STK_CTOR, stk_dtor(), STK_DUMP, stk_pop(), and stk_push().
Referenced by main().
test_stack_normal()
void test_stack_normal ()
Tests stack without messing it up.
Definition at line 3 of file test.cpp.
                         {
    log_printf(&log_file, HTML_H2("---Test stack (normal)---\n"));
    Stack stk = {};
    STK_CTOR_CAP(&stk, 256);
    stk_push(&stk, 123);
    STK_DUMP(&stk);
    for (Elem_t i = 0; i < 10; i++)
        stk_push(&stk, i);
    STK_DUMP(&stk);
    for (Elem_t i = 0; i < 20; i++) {
        stk_push(&stk, i);
        Elem_t p = 0;
        stk_pop(&stk, &p);
    }
    STK_DUMP(&stk);
    for (size_t i = 0; i < 5; i++) {
        Elem_t p = 0;
        stk_pop(&stk, &p);
    }
    STK_DUMP(&stk);
    for (size_t i = 0; i < 6; i++) {
        Elem_t p = 0;
        stk_pop(&stk, &p);
    }
    STK_DUMP(&stk);
    stk_dtor(&stk);
    STK_DUMP(&stk);
    log_printf(&log_file, HTML_H2("---Test stack (normal) end---\n"));
}
References HTML_H2, log_file, log_printf(), STK_CTOR_CAP, stk_dtor(), STK_DUMP, stk_pop(), and stk_push().
Referenced by main().